# Generated by Django 2.2.6 on 2019-10-20 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Allow overriding Template and Queue body field types.
TEMPLATE_BODY_FIELD_TYPE = getattr(settings, 'TEMPLATED_EMAILER_QUEUE_BODY_FIELD_TYPE', models.TextField())
QUEUE_BODY_FIELD_TYPE = getattr(settings, 'TEMPLATED_EMAILER_TEMPLATE_BODY_FIELD_TYPE', models.TextField())


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to', models.TextField(blank=True, null=True)),
                ('send_to', models.TextField(blank=True, null=True)),
                ('cc_to', models.TextField(blank=True, null=True)),
                ('bcc_to', models.TextField(blank=True, null=True)),
                ('send_after_minutes', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', TEMPLATE_BODY_FIELD_TYPE),
                ('attachments', models.TextField(blank=True, help_text='Comma separated list of file paths. If it is a URL, must be full proper url form.')),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('send_to_switch_true', models.CharField(blank=True, help_text='Email Address to add to the Send To field when the switch statement is True', max_length=500)),
                ('send_to_switch_false', models.CharField(blank=True, help_text='Email Address to add to the Send To field when the switch statement is False', max_length=500)),
                ('available_contexts', models.TextField(blank=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Template',
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to', models.TextField(blank=True, null=True)),
                ('send_to', models.TextField(blank=True, null=True)),
                ('cc_to', models.TextField(blank=True, null=True)),
                ('bcc_to', models.TextField(blank=True, null=True)),
                ('send_after_minutes', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', QUEUE_BODY_FIELD_TYPE),
                ('attachments', models.TextField(blank=True, help_text='Comma separated list of file paths. If it is a URL, must be full proper url form.')),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('model_one_name', models.CharField(blank=True, max_length=255)),
                ('model_one_id', models.CharField(blank=True, max_length=255)),
                ('model_two_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_two_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('fake_sent', models.BooleanField(default=False)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dte_sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Queue',
            },
        ),
    ]
